//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace IEToolbarEngine.WebReferenceAutoInsurance {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="autoInsuranceDocumentServiceSoapBinding", Namespace="http://impl.cxf.qianye.com/")]
    public partial class autoInsuranceDocumentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallautoInsuranceDocumentServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public autoInsuranceDocumentService() {
            this.Url = global::IEToolbarEngine.Properties.Settings.Default.IEToolbar_WebReferenceAutoInsurance_autoInsuranceDocumentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallautoInsuranceDocumentServiceCompletedEventHandler CallautoInsuranceDocumentServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName="autoInsuranceDocumentService", RequestNamespace="http://services.cxf.qianye.com/", ResponseElementName="autoInsuranceDocumentServiceResponse", ResponseNamespace="http://services.cxf.qianye.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallautoInsuranceDocumentService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string verifyCode, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string companyName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string jsonData) {
            object[] results = this.Invoke("CallautoInsuranceDocumentService", new object[] {
                        verifyCode,
                        companyName,
                        jsonData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallautoInsuranceDocumentServiceAsync(string verifyCode, string companyName, string jsonData) {
            this.CallautoInsuranceDocumentServiceAsync(verifyCode, companyName, jsonData, null);
        }
        
        /// <remarks/>
        public void CallautoInsuranceDocumentServiceAsync(string verifyCode, string companyName, string jsonData, object userState) {
            if ((this.CallautoInsuranceDocumentServiceOperationCompleted == null)) {
                this.CallautoInsuranceDocumentServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallautoInsuranceDocumentServiceOperationCompleted);
            }
            this.InvokeAsync("CallautoInsuranceDocumentService", new object[] {
                        verifyCode,
                        companyName,
                        jsonData}, this.CallautoInsuranceDocumentServiceOperationCompleted, userState);
        }
        
        private void OnCallautoInsuranceDocumentServiceOperationCompleted(object arg) {
            if ((this.CallautoInsuranceDocumentServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallautoInsuranceDocumentServiceCompleted(this, new CallautoInsuranceDocumentServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CallautoInsuranceDocumentServiceCompletedEventHandler(object sender, CallautoInsuranceDocumentServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallautoInsuranceDocumentServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallautoInsuranceDocumentServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591